# This workflow runs flake8 linting.

name: Run linting
on:
  workflow_call:
    inputs:
      os:
        description: "Target os to run linting on."
        default: "ubuntu-latest"
        required: false
        type: string
      python-version:
        description: "Python version used for linting."
        default: 3.8
        required: false
        type: number
jobs:
  linintg:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=96 --statistics


