# This workflow runs flake8 linting.

name: Run linting
on:
  workflow_call:
    inputs:
      os:
        description: "Target os to run linting on."
        default: "ubuntu-latest"
        required: false
        type: string
      python-version:
        description: "Python version used for linting."
        default: "3.10"
        required: false
        type: string
jobs:
  linting:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=96 --statistics