# This workflow will run a test suite.

name: Run Tests
on:
  workflow_call:
    inputs:
      platforms:
        description: "Target os to run tests on."
        default: "[ 'ubuntu-latest', 'windows-latest', 'macOS-latest' ]"
        required: false
        type: string
      python-versions:
        description: "Array of python versions to run tests on."
        default: "[ '3.10', '3.11', '3.12', '3.13' ]"
        required: false
        type: string
      pytest-args:
        description: "Parameters passed to pytest."
        default: ""
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
        os: ${{ fromJSON(inputs.platforms) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv venv

      - name: Test with pytest
        run: uv run pytest ${{ inputs.pytest-args }}
