# This workflow runs flake8 linting.

name: Run linting
on:
  workflow_call:
    inputs:
      os:
        description: "Target os to run linting on."
        default: "ubuntu-latest"
        required: false
        type: string
      python-version:
        description: "Python version used for linting."
        default: "3.13"
        required: false
        type: string
jobs:
  linting:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Lint code
        run: uvx ruff check
